name: 🔒 Security Issue
description: Report a security vulnerability
title: "[Security]: "
labels: ["security", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Please do not report security vulnerabilities through public GitHub issues.**
        
        If you believe you have found a security vulnerability, please report it via our security policy.
        We will investigate all legitimate reports and do our best to quickly fix the problem.

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Please provide a detailed description of the security issue
      placeholder: Describe the security vulnerability...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe do you consider this vulnerability?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this vulnerability?
      placeholder: Describe the potential impact...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be reproduced?
      placeholder: |
        1. Step one...
        2. Step two...
        3. Step three...
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have any suggestions for how to fix this issue?
      placeholder: Suggested fix or mitigation...

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm your commitment to responsible disclosure
      options:
        - label: I will not publicly disclose this vulnerability until it has been addressed
          required: true
        - label: I understand that this issue will be handled according to the project's security policy
          required: true